spring.application.name=ATx2.4SoftwarearchitectuurKwaliteit

# Logging
logging.level.root=INFO
logging.level.com.example.atx24softwarearchitectuurkwaliteit=DEBUG

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Jackson JSON
# spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Scheduling
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=task-

# Appointment Polling Configuration
app.polling.enabled=true
app.polling.interval-seconds=300
app.polling.initial-delay-seconds=60

# Multitenancy
app.multitenancy.enabled=true


#swiftsend
providers.base-url=${PROVIDERS_BASE_URL:http://localhost:1337}
providers.student-groups=${PROVIDERS_STUDENT_GROUPS:group-c1}
providers.swift-api-keys=${PROVIDERS_SWIFT_API_KEYS:default-api-key}
